import { LanguageProvider } from './context/LanguageContext';
import './globals.css'

export const metadata = {
  title: 'Bartle Test App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <LanguageProvider> {/* Wrap your app with LanguageProvider */}
          {children}
        </LanguageProvider>
      </body>
    </html>
  )
}